# ANN 

We are making use of keras digits datasets

In [ ]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('bank-additional-full.csv', sep = ";")

In [ ]:
df.drop(['month','day_of_week'], axis = 1, inplace = True)

In [ ]:
df

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,334,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,383,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,189,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,442,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,239,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [ ]:
df_no = df[df['y'] == 'no']
df_yes = df[df['y'] == 'yes']

df_no = df_no.sample(frac = 0.125)

df = df_no.append(df_yes, ignore_index = True)

<ipython-input-6-bac9cd3f2ddc>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df_no.append(df_yes, ignore_index = True)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
def func(x):
    if(x=='no'):
        return 0
    else:
        return 1

X = df.loc[:, df.columns!='y']
y = df['y'].apply(lambda x: func(x))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

#### OHE in Training Data

In [ ]:
df_job = pd.get_dummies(X_train['job'])
df_marital = pd.get_dummies(X_train['marital'])
df_marital = df_marital.rename(columns = {'unknown': 'mariatl_unknown'})
df_education = pd.get_dummies(X_train['education'])
df_education = df_education.rename(columns = {'unknown': 'education_unknown'})
df_default = pd.get_dummies(X_train['default'])
df_default = df_default.rename(columns = {'unknown': 'default_unknown', 'no': 'default_no', 'yes': 'default_yes'})
df_housing = pd.get_dummies(X_train['housing'])
df_housing = df_housing.rename(columns = {'unknown': 'housing_unknown', 'no': 'housing_no', 'yes': 'housing_yes'})
df_loan = pd.get_dummies(X_train['loan'])
df_loan = df_loan.rename(columns = {'unknown': 'loan_unknown', 'no': 'loan_no', 'yes': 'loan_yes'})
df_contact = pd.get_dummies(X_train['contact'])
df_poutcome = pd.get_dummies(X_train['poutcome'])

In [ ]:
X_train = X_train.drop(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'poutcome'], axis = 1)

In [ ]:
X_train = X_train.join(df_job)
X_train = X_train.join(df_marital)
X_train = X_train.join(df_education)
X_train = X_train.join(df_default)
X_train = X_train.join(df_housing)
X_train = X_train.join(df_loan)
X_train = X_train.join(df_contact)
X_train = X_train.join(df_poutcome)

#### OHE in testing Data

In [ ]:
df_job = pd.get_dummies(X_test['job'])
df_marital = pd.get_dummies(X_test['marital'])
df_marital = df_marital.rename(columns = {'unknown': 'mariatl_unknown'})
df_education = pd.get_dummies(X_test['education'])
df_education = df_education.rename(columns = {'unknown': 'education_unknown'})
df_default = pd.get_dummies(X_test['default'])
df_default = df_default.rename(columns = {'unknown': 'default_unknown', 'no': 'default_no', 'yes': 'default_yes'})
df_housing = pd.get_dummies(X_test['housing'])
df_housing = df_housing.rename(columns = {'unknown': 'housing_unknown', 'no': 'housing_no', 'yes': 'housing_yes'})
df_loan = pd.get_dummies(X_test['loan'])
df_loan = df_loan.rename(columns = {'unknown': 'loan_unknown', 'no': 'loan_no', 'yes': 'loan_yes'})
df_contact = pd.get_dummies(X_test['contact'])
df_poutcome = pd.get_dummies(X_test['poutcome'])

In [ ]:
X_test = X_test.drop(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'poutcome'], axis = 1)

In [ ]:
X_test = X_test.join(df_job)
X_test = X_test.join(df_marital)
X_test = X_test.join(df_education)
X_test = X_test.join(df_default)
X_test = X_test.join(df_housing)
X_test = X_test.join(df_loan)
X_test = X_test.join(df_contact)
X_test = X_test.join(df_poutcome)

In [ ]:
'''df_job = pd.get_dummies(df['job'])
df_marital = pd.get_dummies(df['marital'])
df_marital = df_marital.rename(columns = {'unknown': 'mariatl_unknown'})
df_education = pd.get_dummies(df['education'])
df_education = df_education.rename(columns = {'unknown': 'education_unknown'})
df_default = pd.get_dummies(df['default'])
df_default = df_default.rename(columns = {'unknown': 'default_unknown', 'no': 'default_no', 'yes': 'default_yes'})
df_housing = pd.get_dummies(df['housing'])
df_housing = df_housing.rename(columns = {'unknown': 'housing_unknown', 'no': 'housing_no', 'yes': 'housing_yes'})
df_loan = pd.get_dummies(df['loan'])
df_loan = df_loan.rename(columns = {'unknown': 'loan_unknown', 'no': 'loan_no', 'yes': 'loan_yes'})
df_contact = pd.get_dummies(df['contact'])
df_poutcome = pd.get_dummies(df['poutcome'])'''

## Creating the Neural Network

In [ ]:
X_train_flattened

array([[ 28., 312.,   2., ...,   0.,   0.,   0.],
       [ 48.,  95.,   1., ...,   0.,   0.,   0.],
       [ 52., 268.,   1., ...,   0.,   0.,   0.],
       ...,
       [ 32., 432.,   3., ...,   1.,   0.,   0.],
       [ 31., 213.,   1., ...,   0.,   0.,   0.],
       [ 42.,  96.,   1., ...,   1.,   0.,   0.]])

In [ ]:
X_train.shape

(6906, 47)

In [ ]:
from keras import backend as K

def recall_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    recall = true_positives / (possible_positives + K.epsilon())
    return recall

def precision_m(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
    precision = true_positives / (predicted_positives + K.epsilon())
    return precision

def f1_m(y_true, y_pred):
    precision = precision_m(y_true, y_pred)
    recall = recall_m(y_true, y_pred)
    return 2*((precision*recall)/(precision+recall+K.epsilon()))

model = keras.Sequential([
    keras.layers.Dense(10, input_shape = (47,), activation = 'relu'),
    keras.layers.Dense(10, input_shape = (10,), activation = 'relu'),
    keras.layers.Dense(10, input_shape = (10,), activation = 'relu'),
    keras.layers.Dense(10, input_shape = (10,), activation = 'relu'),
    keras.layers.Dense(10, input_shape = (10,), activation = 'relu'),
    keras.layers.Dense(2, activation = 'sigmoid')
])

model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['acc', f1_m])

model.fit(X_train, y_train, epochs = 100)

Epoch 1/100
216/216 [==============================] - 3s 4ms/step - loss: 7.2823 - acc: 0.5009 - f1_m: 0.7885
Epoch 2/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4673 - acc: 0.5009 - f1_m: 0.7942
Epoch 3/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4415 - acc: 0.5009 - f1_m: 0.7943
Epoch 4/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4450 - acc: 0.5009 - f1_m: 0.7950
Epoch 5/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4275 - acc: 0.5009 - f1_m: 0.7948
Epoch 6/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4103 - acc: 0.5009 - f1_m: 0.7945
Epoch 7/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4150 - acc: 0.5009 - f1_m: 0.7953
Epoch 8/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3962 - acc: 0.5009 - f1_m: 0.7953
Epoch 9/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3774 - acc: 0.5009 - f1_m: 0.7956
Epoch 10/100
216/216 [==============================] - 1s 4ms/step - loss: 0.4120 - acc: 0.5009 - f1_m: 0.7952
Epoch 11/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3746 - acc: 0.5009 - f1_m: 0.7956
Epoch 12/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3712 - acc: 0.5009 - f1_m: 0.7952
Epoch 13/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3811 - acc: 0.5009 - f1_m: 0.7945
Epoch 14/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3810 - acc: 0.5009 - f1_m: 0.7953
Epoch 15/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3707 - acc: 0.5009 - f1_m: 0.7950
Epoch 16/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3971 - acc: 0.5009 - f1_m: 0.7951
Epoch 17/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3617 - acc: 0.5023 - f1_m: 0.7948
Epoch 18/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3647 - acc: 0.5358 - f1_m: 0.7951
Epoch 19/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3679 - acc: 0.5714 - f1_m: 0.7954: 0s - loss: 0.3691 - acc: 0.5690 - f1_m: 0.
Epoch 20/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3641 - acc: 0.5909 - f1_m: 0.7949: 0s - loss: 0.3615 - acc: 0.5883 - f1
Epoch 21/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3611 - acc: 0.5947 - f1_m: 0.7957
Epoch 22/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3747 - acc: 0.5964 - f1_m: 0.7948
Epoch 23/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3664 - acc: 0.6328 - f1_m: 0.7955
Epoch 24/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3612 - acc: 0.6784 - f1_m: 0.7952
Epoch 25/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3593 - acc: 0.7695 - f1_m: 0.7948
Epoch 26/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3676 - acc: 0.8332 - f1_m: 0.7951
Epoch 27/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3536 - acc: 0.8524 - f1_m: 0.7951
Epoch 28/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3601 - acc: 0.8445 - f1_m: 0.7945
Epoch 29/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3615 - acc: 0.8500 - f1_m: 0.7948
Epoch 30/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3625 - acc: 0.8461 - f1_m: 0.7948
Epoch 31/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3521 - acc: 0.8538 - f1_m: 0.7947
Epoch 32/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3520 - acc: 0.8564 - f1_m: 0.7943
Epoch 33/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3565 - acc: 0.8506 - f1_m: 0.7948
Epoch 34/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3494 - acc: 0.8607 - f1_m: 0.7948
Epoch 35/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3464 - acc: 0.8568 - f1_m: 0.7977
Epoch 36/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3535 - acc: 0.8498 - f1_m: 0.7980
Epoch 37/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3549 - acc: 0.8497 - f1_m: 0.7973
Epoch 38/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3533 - acc: 0.8467 - f1_m: 0.8279
Epoch 39/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3540 - acc: 0.8540 - f1_m: 0.8139
Epoch 40/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3414 - acc: 0.8584 - f1_m: 0.8346
Epoch 41/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3497 - acc: 0.8546 - f1_m: 0.8353
Epoch 42/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3480 - acc: 0.8538 - f1_m: 0.8513
Epoch 43/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3453 - acc: 0.8595 - f1_m: 0.8445
Epoch 44/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3582 - acc: 0.8507 - f1_m: 0.8341
Epoch 45/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3499 - acc: 0.8574 - f1_m: 0.8454
Epoch 46/100
216/216 [==============================] - 1s 5ms/step - loss: 0.3560 - acc: 0.8504 - f1_m: 0.8488
Epoch 47/100
216/216 [==============================] - 1s 5ms/step - loss: 0.3435 - acc: 0.8587 - f1_m: 0.8420
Epoch 48/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3522 - acc: 0.8524 - f1_m: 0.8455
Epoch 49/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3406 - acc: 0.8613 - f1_m: 0.8543
Epoch 50/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3502 - acc: 0.8529 - f1_m: 0.8428
Epoch 51/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3476 - acc: 0.8575 - f1_m: 0.8498: 0s - loss: 0.354
Epoch 52/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3465 - acc: 0.8540 - f1_m: 0.8520
Epoch 53/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3479 - acc: 0.8565 - f1_m: 0.8558: 0s - loss: 0.3404 - acc: 0.8
Epoch 54/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3436 - acc: 0.8603 - f1_m: 0.8580
Epoch 55/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3450 - acc: 0.8587 - f1_m: 0.8511
Epoch 56/100
216/216 [==============================] - 1s 5ms/step - loss: 0.3552 - acc: 0.8507 - f1_m: 0.8483: 0s - loss: 0.3605 - acc: 0.8498 - f1_m
Epoch 57/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3495 - acc: 0.8543 - f1_m: 0.8594
Epoch 58/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3492 - acc: 0.8568 - f1_m: 0.8619
Epoch 59/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3704 - acc: 0.8477 - f1_m: 0.8516
Epoch 60/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3518 - acc: 0.8507 - f1_m: 0.8580
Epoch 61/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3433 - acc: 0.8604 - f1_m: 0.8605: 0s - loss: 0.3410 - acc: 0.8605
Epoch 62/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3476 - acc: 0.8545 - f1_m: 0.8602
Epoch 63/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3443 - acc: 0.8574 - f1_m: 0.8651
Epoch 64/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3402 - acc: 0.8593 - f1_m: 0.8633
Epoch 65/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3477 - acc: 0.8548 - f1_m: 0.8562
Epoch 66/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3529 - acc: 0.8572 - f1_m: 0.8574
Epoch 67/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3519 - acc: 0.8551 - f1_m: 0.8582
Epoch 68/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3509 - acc: 0.8527 - f1_m: 0.8616: 0s - loss: 0.3482 -
Epoch 69/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3441 - acc: 0.8585 - f1_m: 0.8621
Epoch 70/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3409 - acc: 0.8590 - f1_m: 0.8655: 0s - loss: 0.3446 - acc: 0.856
Epoch 71/100

216/216 [==============================] - 1s 4ms/step - loss: 0.3467 - acc: 0.8581 - f1_m: 0.8619
Epoch 72/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3479 - acc: 0.8577 - f1_m: 0.8558
Epoch 73/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3480 - acc: 0.8591 - f1_m: 0.8596
Epoch 74/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3413 - acc: 0.8604 - f1_m: 0.8643
Epoch 75/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3413 - acc: 0.8574 - f1_m: 0.9089
Epoch 76/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3420 - acc: 0.8591 - f1_m: 0.9027
Epoch 77/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3400 - acc: 0.8614 - f1_m: 0.9084
Epoch 78/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3415 - acc: 0.8584 - f1_m: 0.9042
Epoch 79/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3426 - acc: 0.8582 - f1_m: 0.9056
Epoch 80/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3398 - acc: 0.8614 - f1_m: 0.9102
Epoch 81/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3475 - acc: 0.8556 - f1_m: 0.9100
Epoch 82/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3499 - acc: 0.8572 - f1_m: 0.9140
Epoch 83/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3398 - acc: 0.8574 - f1_m: 0.9136
Epoch 84/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3390 - acc: 0.8614 - f1_m: 0.9157
Epoch 85/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3407 - acc: 0.8590 - f1_m: 0.9144
Epoch 86/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3407 - acc: 0.8600 - f1_m: 0.9123
Epoch 87/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3429 - acc: 0.8606 - f1_m: 0.9136
Epoch 88/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3435 - acc: 0.8616 - f1_m: 0.9181
Epoch 89/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3376 - acc: 0.8581 - f1_m: 0.9136
Epoch 90/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3415 - acc: 0.8568 - f1_m: 0.9094
Epoch 91/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3390 - acc: 0.8603 - f1_m: 0.9173
Epoch 92/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3376 - acc: 0.8607 - f1_m: 0.9151
Epoch 93/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3445 - acc: 0.8574 - f1_m: 0.9152
Epoch 94/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3403 - acc: 0.8594 - f1_m: 0.9163
Epoch 95/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3426 - acc: 0.8585 - f1_m: 0.8608
Epoch 96/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3364 - acc: 0.8604 - f1_m: 0.8594
Epoch 97/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3413 - acc: 0.8565 - f1_m: 0.8606
Epoch 98/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3384 - acc: 0.8616 - f1_m: 0.8638
Epoch 99/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3402 - acc: 0.8591 - f1_m: 0.8595
Epoch 100/100
216/216 [==============================] - 1s 4ms/step - loss: 0.3427 - acc: 0.8578 - f1_m: 0.8628